branch_data:
  cicd:
    approvers:
    - GreatBat67
    dcm_dir: dcm_automation
    dcm_target: PEPSI_DCM_CICD
    require_pr: true
    required_approvals: 1
    sf_databases:
    - PEPSI_DEVOPS_DB_CICD
    sf_roles:
    - DBA_ADMIN
    - DBA_FR
    sf_schemas: &id001
    - UTILITIES
    - PATIENTS
    - MANAGEMENT
    sf_user: github_pepsi_cicd_user
  dcm_project:
    approvers: []
    dcm_dir: dcm_automation
    dcm_target: DCM_METADATA
    is_default: true
    is_default_target: true
    is_default_true: true
    require_pr: false
    required_approvals: 0
    sf_databases:
    - CICD_METADATA
    sf_roles:
    - DBA_ADMIN
    - DBA_FR
    sf_schemas:
    - DCM_CONFIG
    sf_user: github_pepsi_project_user
  dev:
    approvers: []
    dcm_dir: dcm_automation
    dcm_target: PEPSI_DCM_DEV
    require_pr: false
    required_approvals: 0
    sf_databases:
    - PEPSI_DEVOPS_DB_DEV
    sf_roles:
    - DBA_ADMIN
    - DBA_FR
    sf_schemas: *id001
    sf_user: github_pepsi_dev_user
  main:
    approvers:
    - GreatBat67
    dcm_dir: dcm_automation
    dcm_target: PEPSI_DCM_MAIN
    require_pr: true
    required_approvals: 1
    sf_databases:
    - PEPSI_DEVOPS_DB_MAIN
    sf_roles:
    - DBA_ADMIN
    - DBA_FR
    sf_schemas: *id001
    sf_user: github_pepsi_main_user
  qa:
    approvers:
    - GreatBat67
    dcm_dir: dcm_automation
    dcm_target: PEPSI_DCM_QA
    require_pr: true
    required_approvals: 1
    sf_databases:
    - PEPSI_DEVOPS_DB_QA
    sf_roles:
    - DBA_ADMIN
    - DBA_FR
    sf_schemas: *id001
    sf_user: github_pepsi_qa_user
branch_sequence:
- dev
- qa
- cicd
- main
- dcm_project
dcm_dir: dcm_automation
dcm_project_name: dcm_automation
escape_protection_branches: []
github:
  files_to_copy:
  - requirements.txt
  - snowflake.toml
  folders_to_copy:
  - Projects
  - dcm_scripts_template
  - helper_scripts
  - dcm_automation
  repo_visibility: public
  source_branch: dcm_template_v1
  source_repository: https://github.com/kipibi/CI_CD_STANDARD_TIER_OFFERING_TEMPLATE
owner: GreatBat67
project: pepsi
project_description: Snowflake Gated GitOps Core Offering
repo_name: pepsi_cicd
roles:
  DBA_ADMIN:
    create: true
    ownership: true
    read: true
  DBA_FR:
    create: true
    ownership: false
    read: true
setup_dcm: true
setup_repo: true
setup_snowflake: true
snowflake_global:
  account_identifier: KIPI-KIPI_PRIMARY
  admin_role: PSEUDO_ACCOUNTADMIN
  warehouse: github_cicd_demo_wh
